# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Navid Reyhanian"
title_separator          : "-"
name                     : &name "Navid Reyhanian"
description              : &description "Wireless Systems Engineer at Cisco"
url                      : https://navidreyhanian.github.io # the base hostname & protocol for your site
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "navidreyhanian/navidreyhanian.github.io"

# Site Author
author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Navid Reyhanian"
  pronouns         : # example: "she/her"  
  bio              : "Wireless Systems Engineer in Cisco's Product Group of Enterprise Networking"
  location         : "Milpitas, CA"
  employer         : "Cisco Systems, Inc."
  uri              : # URL
  email            : "navid.reyhanian@gmail.com" 

  # Academic websites
  arxiv            : # URL
  googlescholar    : "https://scholar.google.com/citations?user=YOURUSERID"
  impactstory      : # URL
  orcid            : # "http://orcid.org/yourorcidurl"
  semantic         : # URL
  pubmed           : # "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  researchgate     : # URL
  scopus           : # URL

  # Repositories and software development
  bitbucket        : # Username
  codepen          : # Username
  dribbble         : # Username
  github           : "navidreyhanian"
  kaggle           : # Username  
  stackoverflow    : # User number or user number and name

  # Social media
  linkedin         : "navid-reyhanian" # Update with your LinkedIn username